---

sudo: required

services:
  - docker

before_install:
  - docker build -t docker-alpine-firefox .

install:
    - docker run -d --name alpine-firefox docker-alpine-firefox

script:
  - docker ps -a | grep -q alpine-grafana
